spring:
  application:
    name: products-manager

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  thymeleaf:
    cache: false

# Logging
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.core.simple: DEBUG
